steps:
  - uses: actions/checkout@v4
  - uses: actions/setup-java@v4
    with:
      java-version: '7'
      distribution: 'temurin'

  - name: Setup Gradle
    uses: gradle/actions/setup-gradle@dbbdc275be76ac10734476cc723d82dfe7ec6eda # v3.4.2

  - name: Build with Gradle
    run: ./gradlew -b ci.gradle build
